import jsPDF from "jspdf";

const BRAND_COLOR: [number, number, number] = [14, 165, 233]; // primary sky-500ish
const DARK: [number, number, number] = [15, 23, 42];
const GRAY: [number, number, number] = [100, 116, 139];
const LIGHT_BG: [number, number, number] = [241, 245, 249];

const drawHeader = (doc: jsPDF, title: string) => {
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, 210, 36, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("OncoVision AI", 14, 16);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(title, 14, 24);
  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);
  doc.text("CONFIDENTIAL — FOR MEDICAL USE ONLY", 196, 30, { align: "right" });
};

const drawFooter = (doc: jsPDF, page: number) => {
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 280, 196, 280);
  doc.setFontSize(7);
  doc.setTextColor(...GRAY);
  doc.text("This report is generated by an AI system for screening purposes only. Not a substitute for professional medical diagnosis.", 14, 285);
  doc.text(`Page ${page}`, 196, 285, { align: "right" });
};

const sectionTitle = (doc: jsPDF, y: number, text: string): number => {
  doc.setFillColor(...LIGHT_BG);
  doc.roundedRect(14, y, 182, 8, 1, 1, "F");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...DARK);
  doc.text(text, 18, y + 5.5);
  return y + 12;
};

const keyValue = (doc: jsPDF, y: number, key: string, value: string, impact?: string): number => {
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GRAY);
  doc.text(key, 18, y);
  doc.setTextColor(...DARK);
  doc.setFont("helvetica", "bold");
  doc.text(value, 90, y);
  if (impact) {
    const color: [number, number, number] = impact === "high" ? [239, 68, 68] : impact === "moderate" ? [234, 179, 8] : [34, 197, 94];
    doc.setTextColor(...color);
    doc.setFontSize(8);
    doc.text(impact.toUpperCase(), 160, y);
  }
  doc.setTextColor(...DARK);
  return y + 6;
};

export const generateRiskPDF = (formData: {
  age: string;
  gender: string;
  country: string;
  genetic_risk: number[];
  smoking_history: string;
  alcohol_consumption: string;
  radiation_exposure: string;
  head_injury_history: string;
  chronic_illness: string;
  blood_pressure: string;
  diabetes: string;
  family_history: string;
  symptom_severity: number[];
}, score: number, riskLabel: string) => {
  const doc = new jsPDF();
  drawHeader(doc, "Stage 1: Brain Cancer Risk Prediction Report");

  let y = 46;

  // Risk Score
  const scoreColor: [number, number, number] = score < 25 ? [34, 197, 94] : score < 50 ? [234, 179, 8] : score < 75 ? [249, 115, 22] : [239, 68, 68];
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, y, 182, 28, 2, 2, "F");
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...scoreColor);
  doc.text(`${score}`, 30, y + 19);
  doc.setFontSize(14);
  doc.text(`/ 100`, 55, y + 19);
  doc.setFontSize(14);
  doc.text(riskLabel, 90, y + 13);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GRAY);
  doc.text("Overall risk assessment score based on provided patient data", 90, y + 21);
  y += 36;

  // Patient Demographics
  y = sectionTitle(doc, y, "Patient Demographics");
  y = keyValue(doc, y, "Age", formData.age);
  y = keyValue(doc, y, "Gender", formData.gender || "Not specified");
  y = keyValue(doc, y, "Country", formData.country || "Not specified");
  y += 4;

  // Risk Factors
  y = sectionTitle(doc, y, "Risk Factor Analysis");
  y = keyValue(doc, y, "Genetic Risk Score", `${formData.genetic_risk[0]}%`, formData.genetic_risk[0] > 50 ? "high" : formData.genetic_risk[0] > 25 ? "moderate" : "low");
  y = keyValue(doc, y, "Smoking History", formData.smoking_history || "Not specified", formData.smoking_history === "yes" ? "moderate" : "low");
  y = keyValue(doc, y, "Alcohol Consumption", formData.alcohol_consumption || "Not specified", formData.alcohol_consumption === "heavy" ? "high" : formData.alcohol_consumption === "moderate" ? "moderate" : "low");
  y = keyValue(doc, y, "Radiation Exposure", formData.radiation_exposure || "Not specified", formData.radiation_exposure === "yes" ? "high" : "low");
  y = keyValue(doc, y, "Head Injury History", formData.head_injury_history || "Not specified", formData.head_injury_history === "yes" ? "moderate" : "low");
  y = keyValue(doc, y, "Chronic Illness", formData.chronic_illness || "Not specified", formData.chronic_illness === "yes" ? "moderate" : "low");
  y += 4;

  // Medical History
  y = sectionTitle(doc, y, "Medical History");
  y = keyValue(doc, y, "Blood Pressure", formData.blood_pressure || "Not specified", formData.blood_pressure === "high" ? "moderate" : "low");
  y = keyValue(doc, y, "Diabetes", formData.diabetes || "Not specified", formData.diabetes === "yes" ? "moderate" : "low");
  y = keyValue(doc, y, "Family History of Cancer", formData.family_history || "Not specified", formData.family_history === "yes" ? "high" : "low");
  y = keyValue(doc, y, "Symptom Severity", `${formData.symptom_severity[0]} / 10`, formData.symptom_severity[0] > 7 ? "high" : formData.symptom_severity[0] > 4 ? "moderate" : "low");
  y += 6;

  // Recommendation
  y = sectionTitle(doc, y, "Recommendation");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...DARK);
  const rec = score >= 75
    ? "CRITICAL: Significant risk factors identified. Immediate specialist consultation strongly recommended. Proceed to Stage 2 tumor detection."
    : score >= 50
    ? "HIGH RISK: Multiple risk factors detected. We recommend an MRI scan and specialist consultation. Consider Stage 2 tumor detection."
    : score >= 25
    ? "MODERATE: Some risk factors present. Consider scheduling a consultation with a neurologist."
    : "LOW RISK: No significant risk factors detected. Continue regular health screenings.";
  const lines = doc.splitTextToSize(rec, 170);
  doc.text(lines, 18, y);

  drawFooter(doc, 1);
  doc.save("OncoVision_Risk_Report.pdf");
};

export const generateTumorPDF = (result: {
  tumorDetected: boolean;
  tumorType: string;
  confidence: number;
  location: string;
  size: string;
  recommendations: string[];
  segmentationData: { label: string; value: number }[];
}) => {
  const doc = new jsPDF();
  drawHeader(doc, "Stage 2: Tumor Detection Analysis Report");

  let y = 46;

  // Detection Status
  const detected = result.tumorDetected;
  const statusColor: [number, number, number] = detected ? [239, 68, 68] : [34, 197, 94];
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, y, 182, 22, 2, 2, "F");
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...statusColor);
  doc.text(detected ? "TUMOR DETECTED" : "NO TUMOR DETECTED", 24, y + 10);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GRAY);
  doc.text(`Confidence: ${result.confidence.toFixed(1)}%`, 24, y + 17);
  y += 30;

  if (detected) {
    // Detection Details
    y = sectionTitle(doc, y, "Detection Details");
    y = keyValue(doc, y, "Tumor Type", result.tumorType);
    y = keyValue(doc, y, "Location", result.location);
    y = keyValue(doc, y, "Estimated Size", result.size);
    y = keyValue(doc, y, "Detection Confidence", `${result.confidence.toFixed(1)}%`);
    y += 4;
  }

  // Segmentation
  y = sectionTitle(doc, y, "Tissue Segmentation");
  result.segmentationData.forEach((s) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...DARK);
    doc.text(s.label, 18, y);
    doc.text(`${s.value.toFixed(1)}%`, 80, y);
    // Progress bar
    doc.setFillColor(226, 232, 240);
    doc.roundedRect(100, y - 3, 90, 4, 1, 1, "F");
    if (s.value > 0) {
      const barColor: [number, number, number] = s.label.includes("Healthy") ? [34, 197, 94] : s.label.includes("Core") ? [239, 68, 68] : s.label.includes("Edema") ? [234, 179, 8] : [249, 115, 22];
      doc.setFillColor(...barColor);
      doc.roundedRect(100, y - 3, Math.max(1, (s.value / 100) * 90), 4, 1, 1, "F");
    }
    y += 8;
  });
  y += 4;

  // Recommendations
  y = sectionTitle(doc, y, "Clinical Recommendations");
  result.recommendations.forEach((r) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...DARK);
    doc.text(`•  ${r}`, 18, y);
    y += 6;
  });

  drawFooter(doc, 1);
  doc.save("OncoVision_Tumor_Report.pdf");
};
